### dev

POST https://p5mw3dsodf.execute-api.ap-northeast-1.amazonaws.com/dev/put

{
    "id":"test12345678",
    "hoge":"fuga"
}


### feature

POST https://7i2gdqkoug.execute-api.ap-northeast-1.amazonaws.com/feature/put

{
    "id":"test345678",
    "hoge":"fuga"
}

### prod

POST https://twc9b861id.execute-api.ap-northeast-1.amazonaws.com/prod/put

{
    "id":"test345678",
    "hoge":"fuga"
}